language: ruby
rvm:
  - 2.1.5
deploy:
  provider: heroku
  api_key:
    secure: <%= ENV['API_SECRET'] %>
  run:
    - 'rake db:migrate'
  app: <%= ENV['HEROKU_APP_NAME'] %>
  on:
    repo: mkondur/netguru-workshops
before_script:
  - export RAILS_ENV=test
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - bundle exec rspec spec